language: c
compiler:
  - gcc
  - clang
script: sh autogen.sh && ./configure --with-boost-suffix="" --with-boost-thread_suffix="" && make && make check
cache:
  - apt
before_install:
  - sudo add-apt-repository -y ppa:jkeiren/ppa
  - sudo add-apt-repository -y ppa:ysbaddaden/ruby-updates
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential autoconf automake libtool pkg-config make ruby2.0
  - sudo apt-get install -y libossp-uuid-dev libpcre3-dev libcurl4-openssl-dev
  - sudo apt-get install -y libboost1.49-dev libboost-chrono1.49-dev libboost-date-time1.49-dev libboost-filesystem1.49-dev libboost-iostreams1.49-dev libboost-program-options1.49-dev libboost-regex1.49-dev libboost-system1.49-dev libboost-thread1.49-dev
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler graphviz
  - sudo apt-get install -y libgeoip-dev geoip-database
  - wget https://launchpad.net/ubuntu/+source/yajl/2.0.4-2/+build/3450133/+files/libyajl2_2.0.4-2_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/yajl/2.0.4-2/+build/3450133/+files/libyajl-dev_2.0.4-2_amd64.deb
  - sudo dpkg -i libyajl*.deb
  - sudo apt-get install -y hwloc trafficserver-dev
  - sudo apt-get install -y apache2-dev
  - gem install ruby_protobuf
after_failure:
  - find . -name '*.log' -print -exec cat {} \;
