language: cpp
compiler:
  - gcc
  - clang
script: sh autogen.sh && ./configure && make && make check
cache:
  - apt
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential autoconf automake libtool pkg-config make
  - sudo apt-get install -y libossp-uuid-dev libpcre3-dev libcurl4-openssl-dev libyajl-dev
  - sudo apt-get install -y libboost-all-dev libprotobuf-dev protobuf-compiler graphviz
  - sudo apt-get install -y libgeoip-dev geoip-database
  - sudo apt-get install -y ruby rubygems
  - sudo apt-get install -y hwloc trafficserver-dev
  - sudo apt-get install -y apache2-dev
  - sudo gem install ruby_protobuf
